export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const FIND_PRODUCT_BY_CATEID = 'FIND_PRODUCT_BY_CATEID';


export const FETCH_CATEGORYS = 'FETCH_CATEGORY'; 
export const SAVE_CATE_CODE = 'SAVE_CATE_CODE'; 

export const FETCH_PRODUCTS_FILTER = 'FETCH_PRODUCTS_FILTER';
export const TOTAL_PRODUCTS = 'TOTAL_PRODUCTS';
export const IS_FETCHING = 'IS_FETCHING';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';