export const FETCH_CATEGORYS = 'FETCH_CATEGORYS';
export const SEARCH_CATEGORYS = 'SEARCH_CATEGORYS';
export const FILTER_CATEGORY = 'FILTER_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const FIND_CATEGORY_BY_CATEID = 'FIND_CATEGORY_BY_CATEID';


export const SAVE_CATE_CODE = 'SAVE_CATE_CODE'; 

export const FETCH_CATEGORYS_FILTER = 'FETCH_CATEGORYS_FILTER';
export const TOTAL_CATEGORYS = 'TOTAL_CATEGORYS';
export const FETCH_CATEGORYS_ALL = 'FETCH_CATEGORYS_ALL';

export const IS_FETCHING_CATE = 'IS_FETCHING_CATE';

export const SET_SCOPE = 'SET_SCOPE';